### ISSUE TITLE
Middleware for smooch converstation

### ISSUE THREAD

**Issue by mb-14** [zendesk/sunshine-conversations-web#553]
Is it possible to add a custom middleware to pre-process the messages before they are sent/received by the user?
This would be useful in the following cases:
- Logging messages
- Modifying content
- Rejecting internal messages meant for logging

**Comment by lemieux** [comment]
Are you looking to do this client-side or server-side? 

Client side would mean it works only for this particular instance and server side would mean it would work for all messages and all channels you integrated in your Smooch app.

**Comment by seanpaley** [comment]
Personally, I'd like the ability in the client side for the web messenger specifically to filter old messages from showing.

**Comment by lemieux** [comment]
@seanpaley that's what I thought when I saw #551 . We have something like this in our iOS Messenger and we have plan to introduce the same feature in the Web Messenger. I'll notify the product team about this so they know there are people interested by the feature. I'll close #551 and keep this one open.

**Comment by mb-14** [comment]
@lemieux If there is a way to plug in a middleware in your existing business systems (Example: slack) then a server side interceptor would be preferable. But that seems unlikely, so a client side implementation should work.

**Comment by lemieux** [comment]
Alright, I'll keep you posted once we start working on it for the Web Messenger.

**Comment by DataWearsAHood** [comment]
Just a bit of housekeeping, but before closing this issue we have released a Pipeline API feature that enables middleware to programatically:
* pre-process messages
* [optionally] add metadata to messages
* [optionally] stop messages from being delivered to webhook listeners (filtering)

Please reach out to our sales team or your Zendesk Sunshine Conversations Account Executive for more details on our Orchestration APIs.
