### ISSUE TITLE
Bug : smooch web displays old app name, does not take into account new app name

### ISSUE THREAD

**Issue by Brachamul** [zendesk/sunshine-conversations-web#650]
After changing either the "Name" or "Team Name" in the settings interface of my Smooch app, the web chat is not affected. It keeps displaying the old app label.

**Comment by DataWearsAHood** [comment]
Hello,

Just doing some housekeeping here; It's been quite some time since you reported this issue and we've released many new versions and bug fixes since.
You can reopen the issue with more details/screenshots if this issue is still present in the latest version(s).
