### ISSUE TITLE
embedded mode deferring connect until render is called

### ISSUE THREAD

**Issue by fsalomon** [zendesk/sunshine-conversations-web#654]
Current behavior:
```
Smooch.init({
  ...
  embedded: true
}).then(function() { 
  /* this code will execute when Smooch.render() is completed */
});
```

Desired behavior:
```
Smooch.init({
  ...
  embedded: true
}).then(function() { 
  /* this code will execute regardless if/when Smooch.render() is called */
});
```

Reason:
1. WebMessager 3 did it.
2. I want to have access to the conversation object and events even if chat is not (yet) rendered. For example, render the chat only if there is a new/unread message; otherwise, render the chat only if user clicks a button.

**Comment by mspensieri** [comment]
Thanks for the report. The reason for this change is that in v4.x, the Web Messenger is loaded and executes in an iframe. In embedded mode, the iframe is not created until `render` is called, so the init logic doesn't start executing until that time.

We're investigating options to enable your use case, we'll update this issue with more details at a later date

**Comment by mspensieri** [comment]
As a workaround, you can call `render` and supply a parent node that is outside of the browser viewport, so that the logic can execute and the messenger can load in the background. Then, when you're ready to display, move the iframe back into the viewport

**Comment by DataWearsAHood** [comment]
Just a quick update before closing with housekeeping - that doc update actually did get pushed back in December 2018; thanks for pointing that one out!
