### ISSUE TITLE
connection to 'wss://api.smooch.io/faye failed: 

### ISSUE THREAD

**Issue by Carson12345** [zendesk/sunshine-conversations-web#655]
Error:
_______________________________
WebSocket connection to 'wss://api.smooch.io/faye failed: Error during WebSocket handshake: Unexpected response code: 400 

https://api.smooch.io/faye 400 (Bad Request) cors.js:88 C) Failed to load https://api.smooch.io/faye: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

Origin 'https://www.xxx.com.hk' is therefore not allowed access. The response had HTTP status code 400. 
_______________________________

This happened when I place the websdk on a simple wordpress site, please advise.

**Comment by aleproust** [comment]
I have the same problem on my side.

**Comment by aleproust** [comment]
Hello, bellow the informations on my side
Browser version: Chrome 66.0.3359.181 
![image](https://user-images.githubusercontent.com/1298928/40855443-97f1d568-65a2-11e8-9719-3002a6089b82.png)

![image](https://user-images.githubusercontent.com/1298928/40855327-4b4ccf4c-65a2-11e8-9648-c9e35d4cc97f.png)

**Comment by alavers** [comment]
Ah. @aleproust there are actually two separate 400 bad requests occurring here.

(1) The websocket connection attempt is failing, and Smooch is falling back on long polling.

(2) The long polling attempt is _also_ failing with 400. This is the network log you've screenshotted. I have an idea as to what's causing that and I'll file an internal issue to track that fix.

However, the websocket attempt (1) should not be failing in the first place. Can you show me the headers/request details associated with that `wss://` request? Note that you may have to select the `Frames` tab to get the full view of what's going on.

**Comment by aleproust** [comment]
Hello, here what i've got 
![image](https://user-images.githubusercontent.com/1298928/40863529-2a34156a-65be-11e8-939f-12c2cd3a0563.png)


![image](https://user-images.githubusercontent.com/1298928/40863507-17c128dc-65be-11e8-9ea9-10b8fb3eae13.png)

**Comment by alavers** [comment]
@aleproust Yep, can you click that `Frames` tab and show me what's being sent over the socket?

**Comment by changchanglccc** [comment]
@alavers Hi, i have the same issue on faye, here is the Frames situation.

![faye](https://user-images.githubusercontent.com/14882462/40995206-7099ea28-68cc-11e8-98da-dd04dada0b36.PNG)

**Comment by alavers** [comment]
That `(Opcode -1)` looks odd. The closest clue I've found is this https://github.com/faye/websocket-driver-ruby/issues/41 which tell me much. I have a few more questions for you both:

1. Can you tell me what chrome version you're using?
2. In what context are you hosting the smooch web messenger? E.g is it hosted on a webpage I can visit, or are you running it localhost?
3. Are websockets in general working in your browser? E.g what do you see in the websocket frames when you test at this
site: https://www.websocket.org/echo.html

**Comment by alavers** [comment]
4. What errors do you see reported to the console? @aleproust can you expand the details on that wss error screenshot you posted 4 days ago?

**Comment by alavers** [comment]
(@aleproust Just noticed you did post your browser version already. Thx 👍 )

**Comment by aleproust** [comment]
Hello @alavers thanks for the time you take to help us. 

2. You cannot reach it it's a local project..
3.Everything fine here 

![image](https://user-images.githubusercontent.com/1298928/41047530-bd8bdf5e-697a-11e8-98b4-898fb2c129d1.png)

4. 
![image](https://user-images.githubusercontent.com/1298928/41047619-f641e190-697a-11e8-9024-5aa61332c1ed.png)

**Comment by alavers** [comment]
^And in that test page (https://www.websocket.org/echo.html) do the Connect/Disconnect buttons work? Do you see messages passing to and fro in the Frames tab? Here's what you should expect to see for example:

<img width="1120" alt="screen shot 2018-06-06 at 1 05 55 pm" src="https://user-images.githubusercontent.com/2432382/41053848-b832486c-698a-11e8-96a2-2ba756a9bd87.png">

Regarding #4 I was more asking about the errors logged to the console (the chrome inspector tab titled console). e.g from your original screenshot, I'd love to see this WebSocket error expanded:

![](https://user-images.githubusercontent.com/1298928/40855443-97f1d568-65a2-11e8-9719-3002a6089b82.png)

**Comment by changchanglccc** [comment]
@alavers hey, there are the error details. Thanks for your help :)
![gh1](https://user-images.githubusercontent.com/14882462/41108622-09ae01dc-6a43-11e8-9418-e2dd30c8397c.PNG)
![gh2](https://user-images.githubusercontent.com/14882462/41108628-0c4639be-6a43-11e8-8f50-392c131f5c48.PNG)

**Comment by alavers** [comment]
@changchanglccc  @aleproust Apologies for the lapse of update!

We've since shipped a fix to the fallback issue in [4.12.7](https://github.com/smooch/smooch-web/releases/tag/4.12.7)

I'm still not sure why the websocket transport isn't working for you, however now the web messenger should be successfully falling back to xhr long polling.

We're still investigating the websocket issue, so I'll leave the issue open for now.

**Comment by alavers** [comment]
We've since implemented some better client side websocket reconnection logic, and haven't seen further incidents reported. Closing this issue for now.
