### ISSUE TITLE
Combine integration thumbnails with CSS Sprites

### ISSUE THREAD

**Issue by nathang21** [zendesk/sunshine-conversations-web#656]
**What is the current behavior?**
Smooch downloads each integration icon separately. 

 **Please provide the steps to reproduce and, if possible, a minimal demo of the problem** via
https://plnkr.co, https://codepen.io/, or similar (e.g. a GitHub repository).
https://photos.app.goo.gl/usDGicUXXH4ZfPjP2

 **What is the expected behavior?**
These assets are combined with CSS sprites

 **Please tell us about your environment:**
- Delivery method: CDN
- Version: 4.6.1
- Browser: ALL
- OS: ALL

Combining images into as few files as possible using CSS sprites reduces the number of round-trips and delays in downloading other resources, reduces request overhead, and can reduce the total number of bytes downloaded by a web page.

Pasting here for easy reference:
https://cdn.smooch.io/2b5e86da0f91443e8a83f7883ca9d10f.png
https://cdn.smooch.io/2bc532f57a2074a56fc036334188e40a.png
https://cdn.smooch.io/8ddaae5507ef13e91e228c0494fd0ae1.png
https://cdn.smooch.io/9d69b94a58a6503b6d6723476ebba41e.png
https://cdn.smooch.io/d7e8b61376385a28b28e39f1d540763c.png

**Comment by DataWearsAHood** [comment]
Hello!

Doing some housekeeping and I've confirmed these graphics are still downloaded individually.
I've passed this suggestion along to the product team for consideration; thanks for letting us know!
