### ISSUE TITLE
Removing "Messaging by Smooch" in the footer of chat widget

### ISSUE THREAD

**Issue by ndc466** [zendesk/sunshine-conversations-web#668]
Hi, I've tried doing several different things to remove the footer at the bottom of the chat widget that reads "Messaging by Smooch" but to of no avail and I haven't been able to find any related documentation for doing so. There already seems to be quite a good number of customization options available to developers, is editing the footer element really not one of them?

**Comment by scottanthonymorin** [comment]
Hi Nolan. (@ndc466 )

Thanks for reaching out.

Currently, only our white-labeled SDKs come without the "messaging by Smooch" footer. We don't offer a way to customize the footer in our default SDKs.

Please also be aware that the `issues` tab in this repo is generally reserved for bugs and issues with the code, not customer support. Feel free to reach out to our customer success team for more help and guidance.

**Comment by r-moore** [comment]
Hi Scott, we also need this. I've reached out by email (hello@smooch.io) is that the best way to find out more?

**Comment by DataWearsAHood** [comment]
Anyone can reach our sales team by clicking on the web widget on [our homepage](https://smooch.io/).
