### ISSUE TITLE
Oracle Digital Assistant - startTyping issue

### ISSUE THREAD

**Issue by SherifBashar** [zendesk/sunshine-conversations-web#674]
Hi , I'm integrating with Smooch through Oracle Digital Assistant AppId.

so I'm just using an appId without userId or JWT.

My question is why Smooch.startTyping(); is not working ?

Does it require login or jwt ? and how can I make it work with Oracle appId without login since we don't have an account on Smooch , just integrating with the appId.

Thanks.

**Comment by DataWearsAHood** [comment]
Hello,

[Smooch.startTyping() on the client-side](https://github.com/zendesk/sunshine-conversations-web#starttypingconversationid) will send a typing indicator webhook **to endpoints subscribed in the app config**.
[Sending a typing:start message via API](https://docs.smooch.io/guide/sending-messages/#sending-typing-activity-with-the-api) will activate the `typing` bubbles **on the client-side**.

If you have any further questions, I invite you to follow-up with your contact at Oracle Digital Assistant (the Sunshine Conversations account owner).
