### ISSUE TITLE
How to block a message ?

### ISSUE THREAD

**Issue by SherifBashar** [zendesk/sunshine-conversations-web#677]
Hi ,

I have a case that I want not to send some messages , I want to prevent the plugin to forward the message to Smooch.

Thanks.

**Comment by DataWearsAHood** [comment]
Hi Sherif,

While there isn't a way to block messages from being sent from the client-side, there are a few other options to achieve a similar outcome:
* agent-UI-side (custom agentUI):
    * filter messages (don't display filitered messsages to agents)
* server-side:
    * [optional] call `DELETE @ /messages/:id` to tombstone the message (`message.text` removed)
* middleware [external pipeline processor] :
    * don't call `/continue` for messages to filter, and optionally, add metadata (e.g.: `filtered: true`); message will be added to conversation record, but not sent to listening systems via webhook.
* client-side:
    * add filter metadata to messages (for processing in server-side/agentUI/etc.): e.g.: `filterMe: true|false`

For more info on Pipeline API, please contact your Zendesk Sunshine Conversations Account Executive.
