### ISSUE TITLE
Uploading Image ~ 3MB doesn't render in the messenger

### ISSUE THREAD

**Issue by sgupta3** [zendesk/sunshine-conversations-web#684]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

**I'm submitting a ...**

-  bug report

**What is the current behavior?**

Images that are ~3MB don't render in the messenger transcript for the first time (If you attach the image from the messenger).

**Please provide the steps to reproduce and, if possible, a minimal demo of the problem** via
https://plnkr.co, https://codepen.io/, or similar (e.g. a GitHub repository).
- Setup the bare-minimum version of the web messenger
- Attach an image that is ~3MB
- The image goes through fine but doesn't actual render on the transcript until you tap on the invisible message.

**What is the expected behavior?**

After attaching the image, the image renders fine.

**Please tell us about your environment:**

- CDN
- Release 4.29.1
- Chrome
- OS X Mojava 10.14.4

**Comment by DataWearsAHood** [comment]
FYI: Fixed!
https://github.com/zendesk/sunshine-conversations-web/releases/tag/5.1.4
