### ISSUE TITLE
Typescript - DefinitelyTyped

### ISSUE THREAD

**Issue by jpsorensen** [zendesk/sunshine-conversations-web#694]
I'm working on a Typescript definition file that documents the Smooch interface for the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped) of Typescript definitions. The types and documentation would be based off of the documentation in your readme.

I wanted to check in with your team - as far as you know, has anyone else produced type definitions for your library? I found [this prior issue](https://github.com/zendesk/sunshine-conversations-web/issues/416) about typings for the library, though I believe it was resolved via a different means (without typings being created).

Would your team be okay with me contributing a definition to DefinitelyTyped? It would be a great way for clients using your library with Typescript to get better compile-time guarantees and to get rich guidance from their IDE about your SDK.

I'd be happy to include anyone from your team on the PR if and when I submit to DefinitelyTyped, and would be happy to include anyone from your team in the owners file as well in case you want to contribute corrections or updates.

Thanks!

**Comment by DataWearsAHood** [comment]
Hi @jpsorensen,

Thanks for your interest and effort in building DefinitelyTyped support for our libraries.
While we can’t assume responsibility for testing/maintaining this contribution, you can share this definition with the community.

**Comment by jpsorensen** [comment]
Thanks! Typescript definitions are now available for Smooch via DefinitelyTyped: https://www.npmjs.com/package/@types/smooch
