### ISSUE TITLE
The form blocks the user from typing in new conversation

### ISSUE THREAD

**Issue by SrigowriHaptik** [zendesk/sunshine-conversations-web#697]
Problem with forms

Expected behaviour:
The user is to be blocked from typing in the input field only in the conversation having the form.

Current behaviour:
Input field of every conversation (new and old ones) is blocked if the user has not filled form in some other conversation

Observation:
The issue is because there is a div with id = footer, and it is outside the conversation div.  It should be specific to each conversation.

![chat1](https://user-images.githubusercontent.com/115141850/206677811-c2970947-6ab4-4880-a25d-17b23684e29a.png)
![chat2](https://user-images.githubusercontent.com/115141850/206677817-88df80b9-d109-4e25-9666-c6a078cabd00.png)

**Comment by DataWearsAHood** [comment]
Hello,

This is only supported in the preChatCapture form, not in regular form messages.
Since this product is in maintenance mode, no new features will be added going forward.

It may be possible to modify the UI to disable the text-input field, but this use is not supported.
