### ISSUE TITLE
Web Messenger does not receive unreadCount event if at init time unread count > 0

### ISSUE THREAD

**Issue by barberscott** [zendesk/sunshine-conversations-web#699]
**What is the current behavior?**

When the web messenger is initialized for multiple conversations and the unread count is > 0 at the time of init for the current user, further updates to the unread count do not trigger an unreadCount event meaning that any bindings to that event will not work until the unread count is driven to zero. 

**What is the expected behavior?**

Unread count at init time, if it changes, should trigger an unreadCount event.

**Please tell us about your environment:**

-   Delivery method: CDN
-   Version 5.5.5
-   Browser: Chrome
-   OS: macOS

**Comment by barberscott** [comment]
I now understand the root cause of this.  It's not as I described and we can close this one.

In multiple conversations mode, the event is keyed off the selected conversation in the widget.  So if you are at the conversation selection screen, I was expecting this event to fire when *any* message came into *any* conversation.  That is not what happens.

Instead, this event only fires when a user has selected a particular conversation.  I am going to open a separate issue that there should be an event for the following:

-- There should be an event for updates to the total unread message count.
-- There should be a sound played when ANY conversation receives a new message.

**Comment by wojtiku** [comment]
I just lost a lot of time debugging this and came to the issues. I think this is counter-intuitive. This issue should still be open and either the docs should be updated or another event should be added.

Now it is impossible to implement a global unread counter for embedded mode widget.
