### ISSUE TITLE
CORs error when expired JWT is provided

### ISSUE THREAD

**Issue by vreviglio** [zendesk/sunshine-conversations-web#707]
**For support questions, please visit [our help page](https://smooch.io/help/)**.

This repository's issues are reserved for bug reports only.

**I'm submitting a ...**

-   [x] bug report
-   [ ] support request => Please do not submit support request here, see note at the top of this template.

**What is the current behavior?**

The problem that I am facing is that I am trying to authenticate my users using a JWT that expires. 

The problem is that when the token expires I get a CORs error and the `onInvalidAuth` delegate is never called.

<img width="704" alt="SCR-20240702-kfff" src="https://github.com/zendesk/sunshine-conversations-web/assets/58663011/dcba95f6-2654-4eb5-92c1-7ed1a27cb1ce">

**Please provide the steps to reproduce and, if possible, a minimal demo of the problem** via
https://plnkr.co, https://codepen.io/, or similar (e.g. a GitHub repository).

[Demo in Codegen](https://codepen.io/Valentin-Reviglio/pen/dyExZej)

**What is the expected behavior?**
I expect that once the JWT expires, the `onInvalidAuth` delegate is called to get a new token.

I have tried this using the [Allow CORS](https://chromewebstore.google.com/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en) chrome extension, and when the token expires it works as expected I get a 401 Unauthorized error and the `onInvalidAuth` delegate is called.

**Please tell us about your environment:**

-   Delivery method: [npm]
-   Version (can be found using `Smooch.VERSION` in your browser): 5.5.6
-   Browser: [Chrome  126.0.6478.127 | Firefox 109.0.1 ]
-   OS: [OS X] + version 14.0

**Comment by mspensieri** [comment]
Hi @vreviglio, thanks for the report. We believe this is related to a recent backend change which was subsequently reverted. Can you please try again?

**Comment by vreviglio** [comment]
> Hi @vreviglio, thanks for the report. We believe this is related to a recent backend change which was subsequently reverted. Can you please try again?

Thanks now everything is working as expected!!
